Create CSS in JavaScript
getninjas/dhalsim-js pull request #2
Opened 2018-03-30 19:45 UTC by nathpaiva

To remove dependency of CSS import when use the library, I created a method that add a CSS from JavaScript.

The method use breaking point of gaiden and now the users can customize with own values

2018-03-30 21:35 UTC, iondrimba commented
@nathpaiva I would also update the README part where is says `After install, you will have to add the stylesheet (dist/media-query.css) to your page via link tag or import it to your existing style manifest.` 

Can you verify if we still have 💚 Maintainability and 💚 coverage  😄

2018-03-30 21:37 UTC, iondrimba submitted a review, later dismissed

2018-04-01 02:23 UTC, eduardojmatos commented on spec/index.spec.js
> +      const element = document.querySelector('style');
`const` before anything, when it is possible =D

2018-04-01 02:33 UTC, eduardojmatos requested changes
Just a minor fix.

This PR is very <3, thank you!!! \o/

2018-04-01 02:33 UTC, eduardojmatos commented on src/dhalsim.js
> +    this.wide = defaultOptions.wide;
This assignments are not necessary, because `Object.assign` already assign this properties, with `defaultDhalsimOptions`.

2018-04-01 02:35 UTC, eduardojmatos commented on src/dhalsim.js
> +    this.wide = defaultOptions.wide;
Sorry, `Object.assign`, line 10, are not assigning `this`. We could make some thing directly like this: 

```JavaScript
Object.assign(this, defaultDhalsimOptions, options);
```

And delete const `defaultOptions` =D

2018-04-04 14:49 UTC, iondrimba approved these changes

2018-04-04 16:18 UTC, williamcosta approved these changes
Nice 🚀

2018-04-04 16:30 UTC, felipeorlando approved these changes

2018-04-04 20:52 UTC, eduardojmatos approved these changes

2018-04-05 12:32 UTC, iondrimba approved these changes

2018-04-06 17:12 UTC, merged